apiVersion: v1
kind: Service
metadata:
  name: sayhiwebapi-service
  labels:
    app: sayhiwebapi
spec:
  type: NodePort
  selector:
    app: sayhiwebapi
  ports:
    - protocol: TCP
      port: 80          # Internal service port (cluster-wide)
      targetPort: 8080  # Port your pod listens on
      nodePort: 30080   # External port on each node (access via NodeIP:30080)